services:
  postgres:
    container_name: catalogBook
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
      POSTGRES_DB: book
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
